/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calculadora.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static double *
_suma_1 (suma_1_argument *argp, struct svc_req *rqstp)
{
	return (suma_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_resta_1 (resta_1_argument *argp, struct svc_req *rqstp)
{
	return (resta_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_multiplica_1 (multiplica_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplica_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_divide_1 (divide_1_argument *argp, struct svc_req *rqstp)
{
	return (divide_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_modulo_1 (modulo_1_argument *argp, struct svc_req *rqstp)
{
	return (modulo_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_potencia_1 (potencia_1_argument *argp, struct svc_req *rqstp)
{
	return (potencia_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_raiz_1 (raiz_1_argument *argp, struct svc_req *rqstp)
{
	return (raiz_1_svc(argp->arg1, argp->arg2, rqstp));
}

static int *
_factorial_1 (int  *argp, struct svc_req *rqstp)
{
	return (factorial_1_svc(*argp, rqstp));
}

static double *
_logaritmo_1 (logaritmo_1_argument *argp, struct svc_req *rqstp)
{
	return (logaritmo_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_log_n_1 (int  *argp, struct svc_req *rqstp)
{
	return (log_n_1_svc(*argp, rqstp));
}

static double *
_log10_1 (int  *argp, struct svc_req *rqstp)
{
	return (log10_1_svc(*argp, rqstp));
}

static double *
_seno_1 (double  *argp, struct svc_req *rqstp)
{
	return (seno_1_svc(*argp, rqstp));
}

static double *
_coseno_1 (double  *argp, struct svc_req *rqstp)
{
	return (coseno_1_svc(*argp, rqstp));
}

static double *
_tangente_1 (double  *argp, struct svc_req *rqstp)
{
	return (tangente_1_svc(*argp, rqstp));
}

static double *
_secante_1 (double  *argp, struct svc_req *rqstp)
{
	return (secante_1_svc(*argp, rqstp));
}

static double *
_cosecante_1 (double  *argp, struct svc_req *rqstp)
{
	return (cosecante_1_svc(*argp, rqstp));
}

static double *
_cotangente_1 (double  *argp, struct svc_req *rqstp)
{
	return (cotangente_1_svc(*argp, rqstp));
}

static v *
_sumavectorial_1 (sumavectorial_1_argument *argp, struct svc_req *rqstp)
{
	return (sumavectorial_1_svc(argp->arg1, argp->arg2, rqstp));
}

static v *
_restavectorial_1 (restavectorial_1_argument *argp, struct svc_req *rqstp)
{
	return (restavectorial_1_svc(argp->arg1, argp->arg2, rqstp));
}

static v *
_multiplicaporescalar_1 (multiplicaporescalar_1_argument *argp, struct svc_req *rqstp)
{
	return (multiplicaporescalar_1_svc(argp->arg1, argp->arg2, rqstp));
}

static double *
_productoescalar_1 (productoescalar_1_argument *argp, struct svc_req *rqstp)
{
	return (productoescalar_1_svc(argp->arg1, argp->arg2, rqstp));
}

static v *
_productovectorial_1 (productovectorial_1_argument *argp, struct svc_req *rqstp)
{
	return (productovectorial_1_svc(argp->arg1, argp->arg2, rqstp));
}

static matrix *
_sumamatricial_1 (sumamatricial_1_argument *argp, struct svc_req *rqstp)
{
	return (sumamatricial_1_svc(argp->arg1, argp->arg2, rqstp));
}

static matrix *
_restamatricial_1 (restamatricial_1_argument *argp, struct svc_req *rqstp)
{
	return (restamatricial_1_svc(argp->arg1, argp->arg2, rqstp));
}

static matrix *
_multmatricial_1 (multmatricial_1_argument *argp, struct svc_req *rqstp)
{
	return (multmatricial_1_svc(argp->arg1, argp->arg2, rqstp));
}

static void
calculadora_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		suma_1_argument suma_1_arg;
		resta_1_argument resta_1_arg;
		multiplica_1_argument multiplica_1_arg;
		divide_1_argument divide_1_arg;
		modulo_1_argument modulo_1_arg;
		potencia_1_argument potencia_1_arg;
		raiz_1_argument raiz_1_arg;
		int factorial_1_arg;
		logaritmo_1_argument logaritmo_1_arg;
		int log_n_1_arg;
		int log10_1_arg;
		double seno_1_arg;
		double coseno_1_arg;
		double tangente_1_arg;
		double secante_1_arg;
		double cosecante_1_arg;
		double cotangente_1_arg;
		sumavectorial_1_argument sumavectorial_1_arg;
		restavectorial_1_argument restavectorial_1_arg;
		multiplicaporescalar_1_argument multiplicaporescalar_1_arg;
		productoescalar_1_argument productoescalar_1_arg;
		productovectorial_1_argument productovectorial_1_arg;
		sumamatricial_1_argument sumamatricial_1_arg;
		restamatricial_1_argument restamatricial_1_arg;
		multmatricial_1_argument multmatricial_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMA:
		_xdr_argument = (xdrproc_t) xdr_suma_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _suma_1;
		break;

	case RESTA:
		_xdr_argument = (xdrproc_t) xdr_resta_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _resta_1;
		break;

	case MULTIPLICA:
		_xdr_argument = (xdrproc_t) xdr_multiplica_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _multiplica_1;
		break;

	case DIVIDE:
		_xdr_argument = (xdrproc_t) xdr_divide_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _divide_1;
		break;

	case MODULO:
		_xdr_argument = (xdrproc_t) xdr_modulo_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _modulo_1;
		break;

	case POTENCIA:
		_xdr_argument = (xdrproc_t) xdr_potencia_1_argument;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _potencia_1;
		break;

	case RAIZ:
		_xdr_argument = (xdrproc_t) xdr_raiz_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _raiz_1;
		break;

	case FACTORIAL:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _factorial_1;
		break;

	case LOGARITMO:
		_xdr_argument = (xdrproc_t) xdr_logaritmo_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _logaritmo_1;
		break;

	case LOG_N:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _log_n_1;
		break;

	case LOG10:
		_xdr_argument = (xdrproc_t) xdr_int;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _log10_1;
		break;

	case SENO:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _seno_1;
		break;

	case COSENO:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _coseno_1;
		break;

	case TANGENTE:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _tangente_1;
		break;

	case SECANTE:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _secante_1;
		break;

	case COSECANTE:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _cosecante_1;
		break;

	case COTANGENTE:
		_xdr_argument = (xdrproc_t) xdr_double;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _cotangente_1;
		break;

	case SUMAVECTORIAL:
		_xdr_argument = (xdrproc_t) xdr_sumavectorial_1_argument;
		_xdr_result = (xdrproc_t) xdr_v;
		local = (char *(*)(char *, struct svc_req *)) _sumavectorial_1;
		break;

	case RESTAVECTORIAL:
		_xdr_argument = (xdrproc_t) xdr_restavectorial_1_argument;
		_xdr_result = (xdrproc_t) xdr_v;
		local = (char *(*)(char *, struct svc_req *)) _restavectorial_1;
		break;

	case MULTIPLICAPORESCALAR:
		_xdr_argument = (xdrproc_t) xdr_multiplicaporescalar_1_argument;
		_xdr_result = (xdrproc_t) xdr_v;
		local = (char *(*)(char *, struct svc_req *)) _multiplicaporescalar_1;
		break;

	case PRODUCTOESCALAR:
		_xdr_argument = (xdrproc_t) xdr_productoescalar_1_argument;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _productoescalar_1;
		break;

	case PRODUCTOVECTORIAL:
		_xdr_argument = (xdrproc_t) xdr_productovectorial_1_argument;
		_xdr_result = (xdrproc_t) xdr_v;
		local = (char *(*)(char *, struct svc_req *)) _productovectorial_1;
		break;

	case SUMAMATRICIAL:
		_xdr_argument = (xdrproc_t) xdr_sumamatricial_1_argument;
		_xdr_result = (xdrproc_t) xdr_matrix;
		local = (char *(*)(char *, struct svc_req *)) _sumamatricial_1;
		break;

	case RESTAMATRICIAL:
		_xdr_argument = (xdrproc_t) xdr_restamatricial_1_argument;
		_xdr_result = (xdrproc_t) xdr_matrix;
		local = (char *(*)(char *, struct svc_req *)) _restamatricial_1;
		break;

	case MULTMATRICIAL:
		_xdr_argument = (xdrproc_t) xdr_multmatricial_1_argument;
		_xdr_result = (xdrproc_t) xdr_matrix;
		local = (char *(*)(char *, struct svc_req *)) _multmatricial_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (CALCULADORA, COMPLETA);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, COMPLETA, calculadora_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, COMPLETA, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, CALCULADORA, COMPLETA, calculadora_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (CALCULADORA, COMPLETA, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
