/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calculadora.h"
#include <stdlib.h>


void calculadora_1(char *host, double arg1, char op, double arg2)
{
	CLIENT *clnt;
	double  *result;

#ifndef	DEBUG
	clnt = clnt_create (host, CALCULADORA, BASICA, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	switch(op)
	{
		case '+' : result = suma_1(arg1, arg2, clnt); break;
		case '-' : result = resta_1(arg1, arg2, clnt); break;
		case 'x' : result = multiplica_1(arg1, arg2, clnt); break;
		case '/' : result = divide_1(arg1, arg2, clnt); break;
	}

	if (result == (double *) NULL) 
	{
		clnt_perror (clnt, "call failed");
	}
	else
	{
		printf("Resultado: %f %c %f = %f\n",arg1,op,arg2,*result);
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc != 5) {
		printf ("usage: %s server_host\n arg1 op arg2\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	char op = *argv[3];
	double arg1 = strtod(argv[2], NULL), arg2 = strtod(argv[4], NULL);
	calculadora_1 (host, arg1, op, arg2);
exit (0);
}
